from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
PAGES={
103:("netball-page page-103","Movement and shooting in netball",r'''
<figure class="lesson-figure movement-figure"><img src="images/pg103_im001.jpg" alt="A netball player holds the ball and practises footwork by stepping and turning in different directions."><figcaption><strong>Figure 14:</strong> Movement</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 12</div><p>Do footwork exercises, starting slowly and then quickly.</p></aside>
<h1 id="page-title">(d) <strong>Shooting</strong></h1><p>Shooting is the action of accurately throwing the ball so that it enters the opponent’s goal, as shown in Figure 15. It is an important skill in netball, where only Goal Shooters (GS) and Goal Attackers (GA) are allowed to shoot. To shoot effectively, the player should consider the following:</p><ol class="roman-steps emphasis-list"><li><strong>Holding the ball correctly.</strong> The player should hold the ball with one or two hands, depending on their distance from the net. The fingers should be open to rest the ball on the palms for good control.</li><li><strong>Bending the knees slightly.</strong> The player should bend the knees slightly and then push the body up to gain power for the shot and increase the accuracy of the ball towards the net.</li><li><strong>Aiming the net.</strong> The player’s eyes should be at the top of the net to ensure the ball is directed correctly.</li><li><strong>Releasing the ball.</strong> The ball should be released with a backspin so that it enters the net easily and reduces the possibility of going out.</li></ol>
'''),
104:("netball-page page-104","Shooting and defending in netball",r'''
<figure class="lesson-figure netball-shot"><img src="images/pg104_im001.jpg" alt="A netball player shoots the ball into the hoop; arrows show the jump and the ball moving toward the net."><figcaption><strong>Figure 15:</strong> Shooting the ball into the net</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 13</div><ol class="alpha-list" type="a"><li>Practise shooting from a short distance and then gradually increase the distance.</li><li>Practise shooting from different angles around the goal.</li></ol></aside>
<h1 id="page-title">(e) <strong>Defending</strong></h1><p>Defending is the act of preventing the opposing team from passing the ball or scoring. Defensive players such as the goalkeeper (GK) and goal defender (GD) must be quick and able to read the game in order to stop the opposing team’s attackers. The main types of defending in netball are:</p><ol class="roman-steps emphasis-list"><li><strong>Man-to-man defence:</strong> A player follows an opponent and attempts to block a pass or shot.</li><li><strong>Zonal defence:</strong> Defensive players stay in specific areas to ensure there is no space for the opponents.</li></ol>
'''),
105:("netball-page page-105","Defending activity and exercise",r'''
<figure class="lesson-figure netball-defence"><img src="images/pg105_im001.jpg" alt="A girl defends in netball with her arms wide while another girl holds the ball near the goal post."><figcaption><strong>Figure 16:</strong> Defending in netball</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 14</div><ol class="alpha-list" type="a"><li>Practise defending someone by preventing them from receiving or passing.</li><li>Work with your teammates to practice blocking the area by blocking the opponents’ path.</li></ol></aside>
<aside class="exercise-panel" id="page-title"><div class="panel-title">Exercise 6</div><ol class="number-list"><li>Why is shooting an important skill in netball?</li><li>Explain the importance of footwork in netball.</li></ol></aside>
'''),
106:("netball-page page-106","Basic netball rules and skill-building strategies",r'''
<h1 id="page-title">Basic netball rules</h1><ol class="number-list rule-list"><li>The game is played in four quarters of 15 minutes each. A 3-minutes break is given between the first and second quarters. Players are given a 5-minutes break after the second quarter ends, which marks half time. Between the third and fourth quarters, players rest for another 3 minutes.</li><li>Each team must have seven players on the court. A team may make substitutions with reserve players during breaks or in case of injuries.</li><li>A player is not allowed to run with the ball.</li><li>Scoring is only done within the goal circle by players playing the GS and GA positions.</li><li>A player may not hold the ball for more than three seconds without passing or scoring.</li></ol>
<aside class="exercise-panel"><div class="panel-title">Exercise 7</div><ol class="number-list"><li>Explain at least two basic rules of netball.</li><li>Why is a netball player not allowed to run with the ball?</li><li>What are the only scoring positions in netball?</li></ol></aside>
<h2>Netball skill-building strategies</h2><p>To become a good netball player, it is important to ensure the following strategies:</p><ol class="strategy-list" type="a"><li><strong>Practising regularly.</strong> A player should practice regularly to strengthen their playing skills, such as passing, receiving passes, and shooting. These exercises help improve the accuracy and speed of passing, as well as the ability to receive the ball without dropping it.</li><li><strong>Participating in trial matches at school or out of school:</strong> Participating in trial matches is an excellent way to learn by doing. These matches enhance the experience of playing as a team, help players understand each other’s tactics, and improve communication between them. It also helps to increase confidence and strengthen the ability to make quick decisions during the game.</li><li><strong>Watching netball matches to help learning new techniques:</strong> A player can learn better techniques by watching experienced players through live matches or videos. Watching top-level games helps to understand various techniques such as fast passing, effective tackling, and better</li></ol>
'''),
107:("netball-page page-107","Netball practice and benefits",r'''
<p class="strategy-continuation">scoring opportunities. Moreover, learning new techniques from top players can improve the level of play and increase knowledge of the game.</p><ol class="strategy-list continued-strategy" type="a" start="4"><li><strong>Doing physical exercises like running and jumping:</strong> Physical exercises are important for every netball player as they increase stamina, speed, and strength. Running helps to improve the ability to move quickly on the court, while jumping exercises strengthen the ability to jump high when scoring or catching the ball. These exercises also help to strengthen muscles and reduce the possibility of injuries during the game.</li></ol>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 15</div><ol class="alpha-list" type="a"><li>Collaborate with your peers to play netball for 20 minutes, focusing on the netball skills you have learned.</li><li>Work together with your peers to play a 30-minute netball match, while following all the rules that have been taught.</li></ol></aside>
<h1 id="page-title">Importance of playing netball</h1><p>Netball is a fast-paced game that requires good cooperation between players to achieve victory. Apart from being a recreational game, netball provides many benefits to the individual player and society as a whole. The following are some of the important benefits of playing netball:</p><ol class="strategy-list netball-benefits" type="a"><li><strong>Improves physical health.</strong> Playing netball is one of the best ways to improve physical well-being. This game involves many movements such as running, jumping, and passing the ball, which increase muscle strength, speed, and physical endurance. It also helps to improve the heart and lungs, lose weight, and improve blood circulation, thus reducing the risk of non-communicable diseases such as blood pressure and diabetes.</li><li><strong>Builds cooperation and friendship between players.</strong> Netball is a team game that requires good communication and cooperation between players. Through practice and matches, players learn to help each other, understand each other, and cooperate with the aim of winning the game. This cooperation increases solidarity and everlasting friendships even outside the field of play.</li></ol>
'''),
108:("netball-page page-108","Benefits of netball exercise",r'''
<ol class="strategy-list netball-benefits" id="page-title" type="a" start="3"><li><strong>It helps to enhance discipline and quick decision-making.</strong> Netball players learn to follow the rules of the game and respect the decisions of the referees, which builds discipline and good character. Hence, this game requires making quick decisions, such as passing the ball to a player in a good position or determining the right tackle. This strengthens the ability to think quickly and make the right decisions, not only on the field but also in everyday life.</li><li><strong>It is a job opportunity for players who participate in major competitions.</strong> For players with great talent and hard work, netball can be a source of employment. Players who can participate in major competitions at the national and international levels get the opportunity to play in major leagues and even get scholarships or work contracts. It can also open up other opportunities, such as becoming referees, coaches, or trainers of netball.</li></ol>
<aside class="exercise-panel"><div class="panel-title">Exercise 8</div><ol class="number-list"><li>Explain the three basic equipment of the game in netball.</li><li>Describe three types of passes used in netball.</li><li>Suggest three ways of improving the skills of playing netball.</li></ol></aside>
''')}

TEMPLATE='''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Arts and Sports Pupil's Book Standard Five - page {n}</title><meta name="title-id" content="pg{nnn}_sec001"><meta name="page-section-id" content="{n}"><link href="./content/tailwind_output.css" rel="stylesheet"><link href="./assets/libs/fontawesome/css/all.min.css" rel="stylesheet"><link href="./assets/fonts.css" rel="stylesheet"><link href="./assets/book-pages.css?v=20260827-28" rel="stylesheet"></head><body><main><div id="content" class="opacity-0"><section role="article" aria-label="{label}" data-section-type="semantic-book-page" data-section-id="pg{nnn}_sec001" class="book-page content-page {classes}"><div class="page-inner">{content}</div>{hooks}</section></div></main><div class="page-voice-controls" aria-label="Page voice controls"><button type="button" data-page-read>Read page</button><button type="button" data-page-stop>Stop</button></div><div class="relative z-50" id="interface-container"></div><div class="relative z-50" id="nav-container"></div><script src="./assets/offline-preloader.js?v=audiofix-20260824-1"></script><script src="./assets/scorm.js"></script><script src="./assets/pdf-page-readalong.js?v=audiofix-20260824-1"></script><script src="./assets/base.bundle.local.js?v=audiofix-20260824-1"></script></body></html>'''

for n,(classes,label,content) in PAGES.items():
 p=ROOT/f"pg{n:03d}_sec001.html";old=p.read_text(encoding="utf-8");m=re.search(r'<div class="[^"]*semantic-page-text[^"]*"[^>]*>.*?</div>',old,re.S)
 if not m: raise RuntimeError(p.name)
 hooks=re.sub(r'class="[^"]*semantic-page-text[^"]*"','class="page-narration-hooks semantic-page-text"',m.group(0),count=1).replace('aria-label="Accessible page text"','aria-hidden="true"')
 p.write_text(TEMPLATE.format(n=n,nnn=f"{n:03d}",label=label,classes=classes,content=content.strip(),hooks=hooks)+"\n",encoding="utf-8");print(p.name)
