from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

PAGES = {
91: ("football-page page-91", "Long passing and receiving the ball", r'''
<figure class="lesson-figure football-kick"><img src="images/pg091_im001.jpg" alt="A football boot kicks a ball with the top of the foot to make a long pass."><figcaption><strong>Figure 3:</strong> Kicking a long pass</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 2</div><p>In pairs, practise passing the ball at long distances using the top of the foot.</p></aside>
<h1 id="page-title">(b) <strong>Receiving the ball</strong></h1><p>This is the skill of receiving and controlling the ball using the foot, thigh, chest or head. The main goal is to have complete control of the ball and be able to continue the game by passing or shooting. Receiving the ball correctly requires the skill of using various parts of the body, such as the foot, thigh or chest.</p>
'''),
92: ("football-page page-92", "Receiving and dribbling the ball", r'''
<figure class="lesson-figure receiving-sequence"><div class="figure-row"><img src="images/pg092_im001.jpg" alt="A boy receives a football with his foot."><img src="images/pg092_im002.jpg" alt="A boy receives a football with his thigh."><img src="images/pg092_im003.jpg" alt="A boy receives a football with his chest."></div><figcaption><strong>Figure 4:</strong> Receiving the ball with foot, thigh and chest</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 3</div><ol class="alpha-list" type="a"><li>Practise receiving the ball using the foot, thigh, and chest.</li><li>Take part in a football game, playing with an emphasis on controlling the ball using your feet, thigh and chest.</li></ol></aside>
<h1 id="page-title">(c) <strong>Dribbling</strong></h1><p>Dribbling is the act of controlling the ball while walking or running, allowing the player to maintain possession and move forward. It requires good ball control, speed, and direction. The player must be very careful to control the ball and pass the opponent without risking losing the ball.</p>
<figure class="lesson-figure dribbling-figure"><img src="images/pg092_im005.jpg" alt="A boy dribbles a football forward."><figcaption><strong>Figure 5:</strong> Dribbling the ball</figcaption></figure>
'''),
93: ("football-page page-93", "Dribbling and shooting", r'''
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 4</div><ol class="alpha-list" type="a"><li>Practise dribbling the ball 20 meters by starting slowly and then quickly.</li><li>Practise dribbling the ball through a circle of cones placed on the ground.</li></ol></aside>
<h1 id="page-title">(d) <strong>Shooting</strong></h1><p>Shooting refers to kicking the ball towards the opponent’s goal with the aim of scoring a goal. To shoot effectively, a player must:</p>
<ol class="roman-steps"><li>Kick the ball with power and accuracy, aiming for the angles of the goal to make it difficult for the goalkeeper to catch it.</li><li>Use different parts of the foot (ankle for an accurate shot, upper leg for a powerful shot).</li><li>Position the body in the right direction to get the ball towards the right direction.</li></ol>
<figure class="lesson-figure shooting-figure"><img src="images/pg093_im002.jpg" alt="A football player shoots the ball toward the goal as the goalkeeper gets ready to stop it."><figcaption><strong>Figure 6:</strong> Shooting</figcaption></figure>
'''),
94: ("football-page page-94", "Shooting and defending", r'''
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 5</div><ol class="alpha-list" type="a"><li>Practise shooting the goal from a short distance and then from long distances.</li><li>Practise shooting from different sides of the goal.</li></ol></aside>
<h1 id="page-title">(e) <strong>Defending</strong></h1><p>Refers to the act of preventing the opposing team from possessing the ball and scoring. Players can defend in different ways, such as:</p>
<ol class="roman-steps"><li><strong>Man-to-man defending:</strong> A player follows an opponent closely to prevent them from receiving the ball or shooting the ball.</li><li><strong>Zonal defending:</strong> Players stay in specific areas of the field to ensure that there are no opportunities for the opposing team to penetrate.</li><li><strong>Tackling:</strong> A player takes possession of the ball from the opponent by using the feet, legs or body without committing a foul.</li></ol>
<figure class="lesson-figure defending-figure"><img src="images/pg094_im002.jpg" alt="Two boys play football as one player blocks the other from moving past the ball."><figcaption><strong>Figure 7:</strong> A player blocking the opponent’s path</figcaption></figure>
'''),
95: ("football-page page-95", "Football activities and basic laws", r'''
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activities 6</div><ol class="alpha-list" type="a"><li>Practise defending a player from receiving or passing the ball.</li><li>Work with your teammates to practice zonal defending by blocking the opponents’ path.</li><li>Practise defending the ball safely without committing a foul.</li></ol></aside>
<aside class="exercise-panel"><div class="panel-title">Exercise 2</div><ol class="number-list"><li>Explain the meaning of passing in football.</li><li>Why is dribbling an important skill in football?</li><li>Why is defending important in football?</li></ol></aside>
<h1 id="page-title">Basic laws of football</h1><p>There are 17 laws of football. At this stage, you will learn the following five laws:</p><ol class="number-list law-list"><li>An official football match is played for 90 minutes, 45 minutes per half paced and a 15-minute half-time break.</li><li>In an official match, the number of players for each team is 11 players, including the goalkeeper.</li><li>A goal is scored if the ball completely crosses the goal line.</li><li>Offside occurs when a player receives the ball in front of the opposing team’s defenders without another player of the opposing team other than the goalkeeper.</li><li>A foul happens if a player wrongly plays against an opponent.</li></ol>
<aside class="activity-panel lower-activity"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 7</div><ol class="alpha-list" type="a"><li>Play football with your friends for 30 minutes, focusing on the skills you have learned.</li><li>Play a football match with your friends for 30 minutes, while abiding to all the rules you have learned</li></ol></aside>
'''),
96: ("football-page page-96", "Improving football skills", r'''
<aside class="exercise-panel"><div class="panel-title">Exercise 3</div><ol class="number-list"><li>Describe at least two important rules of football.</li><li>Explain the meaning of a foul and give one example.</li><li>Why is the referee important in a football game?</li></ol></aside>
<h1 id="page-title" class="blue-heading">Strategies for improving football skills</h1><p>To become a good football player, it is important to abide by the following strategies:</p><ol class="strategy-list" type="a"><li><strong>Make a daily practice to help enhance the skill of playing,</strong> for instance, passing and ball control. The player should often practice passing the ball with the right and left foot, as well as practising receiving and controlling the ball, which helps to increase accuracy and speed.</li><li><strong>Participate in trial matches at school or out of school.</strong> Playing trial matches helps to learn cooperative play, improve speed, and understand the tactics of opponents.</li><li><strong>Watch football games and learn new techniques.</strong> A player can learn new techniques by watching football matches, whether live or through videos and television. This helps to understand the techniques of tackling, defending, and playing together as a team.</li><li><strong>Do physical exercises frequently.</strong> Football requires strength, flexibility and endurance, so doing physical exercises such as running, jumping rope, and other physical exercises helps to increase stamina and physical strength.</li></ol>
<h2>Importance of playing football</h2><p>Football is not only a game of entertainment, but it has many other benefits for the individual player and society as a whole. Some of the benefits of playing football are:</p><ol class="strategy-list benefits" type="a"><li><strong>It helps in improving physical health.</strong> Football is a game that involves running, jumping, and performing various movements that strengthen the health of the heart, muscles, and bones. It also helps to reduce the risk of non-communicable diseases such as blood pressure and diabetes.</li><li><strong>It promotes cooperation and friendship among players.</strong> Football is a team game, so players learn to cooperate and help each other to</li></ol>
''')
}

TEMPLATE = '''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Arts and Sports Pupil's Book Standard Five - page {n}</title><meta name="title-id" content="pg{nnn}_sec001"><meta name="page-section-id" content="{n}"><link href="./content/tailwind_output.css" rel="stylesheet"><link href="./assets/libs/fontawesome/css/all.min.css" rel="stylesheet"><link href="./assets/fonts.css" rel="stylesheet"><link href="./assets/book-pages.css?v=20260827-24" rel="stylesheet"></head><body><main><div id="content" class="opacity-0"><section role="article" aria-label="{label}" data-section-type="semantic-book-page" data-section-id="pg{nnn}_sec001" class="book-page content-page {classes}"><div class="page-inner">{content}</div>{hooks}</section></div></main><div class="page-voice-controls" aria-label="Page voice controls"><button type="button" data-page-read>Read page</button><button type="button" data-page-stop>Stop</button></div><div class="relative z-50" id="interface-container"></div><div class="relative z-50" id="nav-container"></div><script src="./assets/offline-preloader.js?v=audiofix-20260824-1"></script><script src="./assets/scorm.js"></script><script src="./assets/pdf-page-readalong.js?v=audiofix-20260824-1"></script><script src="./assets/base.bundle.local.js?v=audiofix-20260824-1"></script></body></html>'''

for n, (classes, label, content) in PAGES.items():
    path = ROOT / f"pg{n:03d}_sec001.html"
    old = path.read_text(encoding="utf-8")
    match = re.search(r'<div class="[^"]*semantic-page-text[^"]*"[^>]*>.*?</div>', old, re.S)
    if not match:
        raise RuntimeError(path.name)
    hooks = re.sub(r'class="[^"]*semantic-page-text[^"]*"', 'class="page-narration-hooks semantic-page-text"', match.group(0), count=1)
    hooks = hooks.replace('aria-label="Accessible page text"', 'aria-hidden="true"')
    path.write_text(TEMPLATE.format(n=n, nnn=f"{n:03d}", label=label, classes=classes, content=content.strip(), hooks=hooks) + "\n", encoding="utf-8")
    print(path.name)
