from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
PAGES={
109:("test-page page-109","Test: multiple-choice questions one to six",r'''
<header class="test-header"><h1 id="page-title">Test</h1><h2>Answer all the questions</h2></header>
<section class="test-section"><div class="question-lead"><strong>1.</strong><p>Answer questions (i) to (x) by choosing the letter of the correct answer and write the chosen letter in the bracket beside the question number.</p></div>
<ol class="multiple-choice" type="i"><li><div class="prompt">What does mime rely mostly?<span class="answer-bracket" aria-label="Answer space">( &nbsp;&nbsp;&nbsp;&nbsp; )</span></div><ol type="A"><li>Sound and music</li><li>Sign language</li><li>Non-verbal communication</li><li>Captivating scripts</li></ol></li><li><div class="prompt">Which of the following is a type of musical dynamics?<span class="answer-bracket" aria-label="Answer space">( &nbsp;&nbsp;&nbsp;&nbsp; )</span></div><ol type="A"><li>Scale</li><li>Crescendo</li><li>Melody</li><li>Harmony</li></ol></li><li><div class="prompt">How many beats does a half note have?</div><ol type="A"><li>1</li><li>2</li><li>4</li><li>8</li></ol></li><li><div class="prompt">How many notes are used in the ascending major scale?<span class="answer-bracket" aria-label="Answer space">( &nbsp;&nbsp;&nbsp;&nbsp; )</span></div><ol type="A"><li>4</li><li>7</li><li>8</li><li>10</li></ol></li><li><div class="prompt">Why is it important to use musical instruments in solfa singing?<span class="answer-bracket" aria-label="Answer space">( &nbsp;&nbsp;&nbsp;&nbsp; )</span></div><ol type="A"><li>To make music difficult</li><li>To help understand pitch and note arrangement</li><li>To make the singers’ voices audible</li><li>To make practice tiresome</li></ol></li><li><div class="prompt">Which among the following notes has the longest duration?<span class="answer-bracket" aria-label="Answer space">( &nbsp;&nbsp;&nbsp;&nbsp; )</span></div><ol type="A"><li>Quarter note</li><li>Half note</li></ol></li></ol></section>
'''),
110:("test-page page-110","Test: multiple-choice questions six to ten",r'''
<section class="test-section continued-test" id="page-title"><ol class="multiple-choice" type="i" start="6"><li class="continued-question"><ol type="A" start="3"><li>Whole note</li><li>Eighth note</li></ol></li><li><div class="prompt">Which of the following are the ascending solfa of the major scale?<span class="answer-bracket" aria-label="Answer space">( &nbsp;&nbsp;&nbsp;&nbsp; )</span></div><ol type="A"><li>do re mi fa so la ti do'</li><li>do' ti la so fa mi re do</li><li>do re fa mi so la si do'</li><li>do re mi fa so la do'</li></ol></li><li><div class="prompt">Which section should be considered when drawing a picture?<span class="answer-bracket" aria-label="Answer space">( &nbsp;&nbsp;&nbsp;&nbsp; )</span></div><ol type="A"><li>Line, balance and shadows</li><li>Eracer, pencil and clay modelling</li><li>Lines, eraser and clay modelling</li><li>Kiln, pencil and balance</li></ol></li><li><div class="prompt">Why is it important for a player to wear their team jersey?<span class="answer-bracket" aria-label="Answer space">( &nbsp;&nbsp;&nbsp;&nbsp; )</span></div><ol type="A"><li>Because of the weather</li><li>Because it represents the team’s identity and unity</li><li>Because it gives them extra strength during the game</li><li>Because it is a rule to wear sportswear</li></ol></li><li><div class="prompt">Which of the following exercise helps to improve a player’s speed?<span class="answer-bracket" aria-label="Answer space">( &nbsp;&nbsp;&nbsp;&nbsp; )</span></div><ol type="A"><li>Squatting</li><li>High knees</li><li>Push-ups</li><li>Broad jump</li></ol></li></ol></section>
'''),
111:("test-page page-111","Test: matching and fill-in questions",r'''
<section class="test-section"><div class="question-lead"><strong>2.</strong><p id="page-title">Match items (i)-(v) from List A with their descriptions in List B</p></div>
<table class="matching-table"><thead><tr><th scope="col">List A</th><th scope="col">List B</th></tr></thead><tbody><tr><td>(i) Mould</td><td>A. Cloth is worn during pottery-making</td></tr><tr><td>(ii) Kiln</td><td>B. Device for transporting pots</td></tr><tr><td>(iii) Rod carrier</td><td>C. Minerals for polishing clay models</td></tr><tr><td>(iv) Glaze</td><td>D. A special area for firing bricks or clay models</td></tr><tr><td>(v) Apron</td><td>E. Tool for making other shapes</td></tr></tbody></table></section>
<section class="test-section fill-section"><div class="question-lead"><strong>3.</strong><p>Complete the following sentences by filling in the blanks provided.</p></div><ol class="fill-list" type="i"><li>A major scale has <span class="blank-line wide" aria-label="blank answer"></span> notes arranged in a regular pattern.</li><li>A half note has <span class="blank-line wide" aria-label="blank answer"></span> beats</li><li>Musical instruments such as <span class="blank-line medium" aria-label="blank answer"></span> and <span class="blank-line medium" aria-label="blank answer"></span> are used to accompany solfa singing</li><li>Narrative literature whose actors are the main characters is <span class="blank-line wide" aria-label="blank answer"></span></li><li>Passing the ball to a teammate correctly is called <span class="blank-line medium" aria-label="blank answer"></span></li></ol></section>
'''),
112:("test-page page-112","Test: true or false and written questions",r'''
<section class="test-section"><div class="question-lead"><strong>4.</strong><p id="page-title">Read the following sentences, then write TRUE if the statement is correct and FALSE if the sentence is incorrect.</p></div><ol class="true-false" type="i"><li>Solfa singing uses solfa syllable such as <em>do, re, mi,</em> <span class="blank-line short" aria-label="answer space"></span></li><li>Defending is an important skill in football, which helps the opponent team to score a goal <span class="blank-line short" aria-label="answer space"></span></li><li>One half of an official football match is played for 45 minutes <span class="blank-line medium" aria-label="answer space"></span></li><li>“<em>Piano</em>” means singing with loud <span class="blank-line short" aria-label="answer space"></span></li><li>A whole note has two beats <span class="blank-line medium" aria-label="answer space"></span></li></ol></section>
<ol class="written-questions" start="5"><li>Explain how playing football can be a job opportunity.</li><li>Name three health benefits of playing football and netball.</li><li>Explain why football boots have spikes.</li><li>Why is footwork important in netball?</li><li>Explain two ways of tackling in netball.</li><li>Explain the importance of musical dynamics in singing.</li><li>What are the challenges you might encounter in solfa singing accompanied by musical instruments?</li><li>Which term and sign for dynamic that can be used to reflect sadness in a song?</li></ol>
''')}

TEMPLATE='''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Arts and Sports Pupil's Book Standard Five - page {n}</title><meta name="title-id" content="pg{nnn}_sec001"><meta name="page-section-id" content="{n}"><link href="./content/tailwind_output.css" rel="stylesheet"><link href="./assets/libs/fontawesome/css/all.min.css" rel="stylesheet"><link href="./assets/fonts.css" rel="stylesheet"><link href="./assets/book-pages.css?v=20260827-31" rel="stylesheet"></head><body><main><div id="content" class="opacity-0"><section role="article" aria-label="{label}" data-section-type="semantic-book-page" data-section-id="pg{nnn}_sec001" class="book-page content-page {classes}"><div class="page-inner">{content}</div>{hooks}</section></div></main><div class="page-voice-controls" aria-label="Page voice controls"><button type="button" data-page-read>Read page</button><button type="button" data-page-stop>Stop</button></div><div class="relative z-50" id="interface-container"></div><div class="relative z-50" id="nav-container"></div><script src="./assets/offline-preloader.js?v=audiofix-20260824-1"></script><script src="./assets/scorm.js"></script><script src="./assets/pdf-page-readalong.js?v=audiofix-20260824-1"></script><script src="./assets/base.bundle.local.js?v=audiofix-20260824-1"></script></body></html>'''
for n,(classes,label,content) in PAGES.items():
 p=ROOT/f"pg{n:03d}_sec001.html";old=p.read_text(encoding="utf-8");m=re.search(r'<div class="[^"]*semantic-page-text[^"]*"[^>]*>.*?</div>',old,re.S)
 if not m: raise RuntimeError(p.name)
 hooks=re.sub(r'class="[^"]*semantic-page-text[^"]*"','class="page-narration-hooks semantic-page-text"',m.group(0),count=1).replace('aria-label="Accessible page text"','aria-hidden="true"')
 hooks=re.sub(r'\s*<span data-id="[^"]+">\(\s*\)</span>','',hooks)
 p.write_text(TEMPLATE.format(n=n,nnn=f"{n:03d}",label=label,classes=classes,content=content.strip(),hooks=hooks)+"\n",encoding="utf-8");print(p.name)
