from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
PAGES = {
97: ("netball-page page-97", "Football benefits and introduction to netball", r'''
<p class="benefit-continuation">achieve their goals. This builds friendship and solidarity among players.</p><ol class="strategy-list continuation-benefits" type="a" start="3"><li><strong>It builds discipline and learns to make quick decisions.</strong> Football players learn to follow the rules, respect referees and fellow players, and make quick decisions when they are on the field. This also helps them in daily life.</li><li><strong>It is a job opportunity for players who can play in major competitions.</strong> Talented and motivated players can get the opportunity to play in major national and international leagues, thus finding employment and improving their lives through football.</li></ol>
<aside class="exercise-panel"><div class="panel-title">Exercise 4</div><ol class="number-list"><li>What is football?</li><li>Name two ways a player can use to learn new football techniques.</li><li>Explain three benefits of playing football.</li></ol></aside>
<h1 id="page-title">Netball</h1><p>Netball is a two-team game played with the aim of scoring goals by passing the ball into the opposing team's net. A team consists of seven players. In netball, every player has his or her own playing area. A player is not allowed to play out of his or her restricted area. Figure 8 shows the playing positions in netball.</p>
<figure class="lesson-figure netball-court"><div class="court-diagram" role="img" aria-label="Netball court showing playing positions: GK and GD in the left third, WD in the left and centre areas, C in the middle, GA and WA in the right and centre areas, and GS in the right goal area."><span class="court-third left"></span><span class="court-third right"></span><span class="goal-circle left"></span><span class="goal-circle right"></span><span class="centre-circle">C</span><span class="pos wd">WD</span><span class="pos gk">GK</span><span class="pos gd">GD</span><span class="pos ga">GA</span><span class="pos gs">GS</span><span class="pos wa">WA</span></div><figcaption><strong>Figure 8:</strong> Playing positions in netball</figcaption></figure>
<dl class="position-list"><div><dt>(a) Goalkeeper (GK):</dt><dd>Is allowed to play in the defensive third and the goal circle.</dd></div></dl>
'''),
98: ("netball-page page-98", "Netball positions and equipment", r'''
<dl class="position-list" id="page-title"><div><dt>(b) Goal defence (GD):</dt><dd>Is allowed to play in a defensive third, goal circle and centre third.</dd></div><div><dt>(c) Wing defence (WD):</dt><dd>Is allowed to play in a defensive third and centre third.</dd></div><div><dt>(d) Centre (C):</dt><dd>Is allowed to play in any area of the field except within his or her own goal circle and that of the opponent.</dd></div><div><dt>(e) Goal attack (GA):</dt><dd>Is allowed to play in the circle of the opposing team, attacking the third and centre third.</dd></div><div><dt>(f) Goal shooter (GS):</dt><dd>Is allowed to play in the goal circle of the opposing team and In the attacking third.</dd></div><div><dt>(g) Wing attack (WA):</dt><dd>Is allowed to play in the centre third and attacking third.</dd></div></dl>
<h1>Equipment</h1><p>To play netball correctly, the following equipment are essential.</p>
<figure class="lesson-figure netball-equipment"><div class="equipment-row"><div><img src="images/pg098_im001.jpg" alt="A white netball with blue and pink stripes."><span>Netball</span></div><div><img src="images/pg098_im002.jpg" alt="A pair of white sports shoes for playing netball."><span>Sports shoes</span></div><div><img src="images/pg098_im003.jpg" alt="Blue netball bibs labelled C, GS, GD, WD, WA, GK, and GA."><span>Bibs</span></div></div><figcaption><strong>Figure 9:</strong> Netball equipment</figcaption></figure>
<aside class="exercise-panel"><div class="panel-title">Exercise 5</div><ol class="number-list"><li>What is netball?</li><li>Explain the use of the netball equipment shown in Figure 9.</li><li>Analyse at least two playing positions of a netball game.</li></ol></aside>
'''),
99: ("netball-page page-99", "Basic netball skills and chest pass", r'''
<h1 id="page-title">Basic skills in the game of netball</h1><p>To be able to play netball well, a player must have the basic skills of the game. The essential netball skills include passing, catching, movements, shooting and defending.</p>
<h2>(a) <strong>Passing</strong></h2><p>Passing is the act of throwing the ball from one player to another of the same team. Passing accurately is essential for a team to attack quickly and prevent opponents from gaining possession of the ball. The main types of passes are chest pass, bounce pass and high pass.</p>
<h3>Chest pass</h3><p>A chest pass is the throwing of the ball, released from the passer’s chest, directly to the teammate’s chest using both hands. The pass is normally quick, easy and accurate to short distances. To be successful, the player must hold the ball with both hands and place it in front of the chest, then push it powerfully and accurately towards the teammate, as shown in Figure 10.</p>
<figure class="lesson-figure pass-figure"><img src="images/pg099_im001.jpg" alt="Two children practise a netball chest pass, throwing the ball straight from one chest to the other."><figcaption><strong>Figure 10:</strong> Practising a chest pass</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 8</div><p>Practice making the chest pass.</p></aside>
'''),
100: ("netball-page page-100", "Bounce pass and high pass", r'''
<h1 id="page-title">Bounce pass</h1><p>A bounce pass is the passing of the ball whereby the ball is thrown so as to bounce once before it reaches the receiving player. The ball is held with two hands while directing it to the bouncing point and released at an angle to bounce hard towards the teammate. This type of pass prevents the opponent from catching it as the ball is strategically directed to a teammate. It is often done for a short distance, as shown in Figure 11.</p>
<figure class="lesson-figure bounce-figure"><img src="images/pg100_im001.jpg" alt="A player bends forward and throws the ball down so it bounces once on the ground and rises to a teammate."><figcaption><strong>Figure 11:</strong> Making a bounce pass</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 9</div><p>Practise making a bounce pass.</p></aside>
<h2>High pass</h2><p>A high pass is the passing of the ball from the top of one player’s head to another player at a distance. This pass is often used when a player needs to deliver the ball over a long distance or when they want the ball to go over the obstacles of the opposing team. To make this pass, the player stands upright, takes the ball with both hands behind the head, and then pushes it forward with force and accuracy to reach the distant player, as shown in Figure 12.</p>
'''),
101: ("netball-page page-101", "High pass and catching the ball", r'''
<figure class="lesson-figure high-pass-figure"><img src="images/pg101_im001.jpg" alt="A player throws a high ball to a teammate with hands raised to catch it."><figcaption><strong>Figure 12:</strong> Practising a high pass</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 10</div><ol class="alpha-list" type="a"><li>Practise high passing.</li><li>In a netball match, play while focusing on high passing skills.</li></ol></aside>
<h1 id="page-title">(a) <strong>Catching and controlling the ball</strong></h1><p>Catching and controlling the ball is an important skill in netball. The skill allows the team to maintain possession of the ball in a game. To achieve effective receiving and controlling the ball, the player should:</p><ol class="roman-steps emphasis-list"><li><strong>Keep the hands open and the fingers pointing forward.</strong> This allows the player to control the ball effectively. Fingers pointing forward help the player to create a shape for receiving the ball easily.</li><li><strong>Absorb the ball’s momentum by softening your hands on impact.</strong> When the ball lands in the hands, the player should slightly pull back the hands to reduce the impact of the collision and keep the ball safe.</li><li><strong>Use the eyes to track the ball to determine its direction:</strong> The player’s eyes should be on the ball at all times to see its direction and prepare to receive it correctly. This also helps to prevent the ball from being lost.</li></ol>
'''),
102: ("netball-page page-102", "Receiving and movement in netball", r'''
<figure class="lesson-figure receiving-pair"><div class="figure-row"><img src="images/pg102_im001.jpg" alt="A player catches the netball with both hands while stepping forward."><img src="images/pg102_im002.jpg" alt="A player receives the netball with one hand while moving forward."></div><figcaption><strong>Figure 13:</strong> Receiving the ball with both hands or one hand</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 11</div><ol class="alpha-list" type="a"><li>Practise catching the ball with one hand and two hands.</li><li>Organise a match and play by considering receiving the ball with one hand and two hands.</li></ol></aside>
<h1 id="page-title">(b) <strong>Movements</strong></h1><p>Movement is an important skill in netball, where players must use their feet carefully to maintain direction and balance. In netball, a player cannot run with the ball, but they can take one or two running steps to change direction and prepare to pass or shoot. Figure 14 shows how to change movements.</p>
''')
}

TEMPLATE='''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Arts and Sports Pupil's Book Standard Five - page {n}</title><meta name="title-id" content="pg{nnn}_sec001"><meta name="page-section-id" content="{n}"><link href="./content/tailwind_output.css" rel="stylesheet"><link href="./assets/libs/fontawesome/css/all.min.css" rel="stylesheet"><link href="./assets/fonts.css" rel="stylesheet"><link href="./assets/book-pages.css?v=20260827-26" rel="stylesheet"></head><body><main><div id="content" class="opacity-0"><section role="article" aria-label="{label}" data-section-type="semantic-book-page" data-section-id="pg{nnn}_sec001" class="book-page content-page {classes}"><div class="page-inner">{content}</div>{hooks}</section></div></main><div class="page-voice-controls" aria-label="Page voice controls"><button type="button" data-page-read>Read page</button><button type="button" data-page-stop>Stop</button></div><div class="relative z-50" id="interface-container"></div><div class="relative z-50" id="nav-container"></div><script src="./assets/offline-preloader.js?v=audiofix-20260824-1"></script><script src="./assets/scorm.js"></script><script src="./assets/pdf-page-readalong.js?v=audiofix-20260824-1"></script><script src="./assets/base.bundle.local.js?v=audiofix-20260824-1"></script></body></html>'''

for n,(classes,label,content) in PAGES.items():
    path=ROOT/f"pg{n:03d}_sec001.html"
    old=path.read_text(encoding="utf-8")
    match=re.search(r'<div class="[^"]*semantic-page-text[^"]*"[^>]*>.*?</div>',old,re.S)
    if not match: raise RuntimeError(path.name)
    hooks=re.sub(r'class="[^"]*semantic-page-text[^"]*"','class="page-narration-hooks semantic-page-text"',match.group(0),count=1).replace('aria-label="Accessible page text"','aria-hidden="true"')
    path.write_text(TEMPLATE.format(n=n,nnn=f"{n:03d}",label=label,classes=classes,content=content.strip(),hooks=hooks)+"\n",encoding="utf-8")
    print(path.name)
