from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
PAGES = {
79: ("exercise-method-page page-79", "Push-up exercise", r'''
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 2</div><ol class="alpha-list" type="a"><li>Do the high knees exercise individually.</li><li>In pairs, practice the high knees exercise.</li></ol></aside>
<h2 id="page-title">(c)&nbsp; <strong>Push-ups</strong></h2><p>Push-up exercise strengthens the muscles of the arms, shoulders and chest. This helps players when participating in sports such as football and netball in making powerful passes as well as competing physically with opponents.</p>
<h3>How to do push-ups:</h3><ol class="roman-steps" type="i"><li>Lie face down and support yourself on your hands and toes;</li><li>Raise your body by pushing up your arms until the arms are fully extended;</li><li>Lower your body slowly near to the floor without touching it; and</li><li>Repeat 10 to 15 times for 3 sets, by following steps (i-iii) as shown in Figure 3.</li></ol>
<figure class="lesson-figure pushup-figure"><div class="exercise-stack"><img src="images/pg079_im002_seg001_v1.png" alt="A boy holds the starting push-up position with straight arms and a straight body."><img src="images/pg079_im002_seg002_v1.png" alt="A boy lowers his body in a push-up, with his arms bent and chest close to the floor."></div><figcaption><strong>Figure 3:</strong> Doing a push-up exercise</figcaption></figure>
'''),
80: ("exercise-method-page page-80", "Plank exercise", r'''
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 3</div><ol class="alpha-list" type="a"><li>Do a push-up exercise individually.</li><li>Compete with your friends to do the push-ups as many times as possible.</li></ol></aside>
<h2 id="page-title">(d)&nbsp; <strong>Planks</strong></h2><p>Planks strengthen the abdominal and back muscles, helping players to be stable when running or jumping.</p><h3>How to do planks:</h3><ol class="roman-steps" type="i"><li>Lie face down, supporting yourself on your hands and toes;</li><li>Keep your body upright; do not let your waist dip or rise; and</li><li>Hold this position for 30 to 60 seconds, then relax and repeat 3 times, by following steps (i-ii) as shown in Figure 4.</li></ol>
<figure class="lesson-figure plank-figure"><img src="images/pg080_im002.jpg" alt="A boy holds a plank with his body straight, resting on his forearms and toes."><figcaption><strong>Figure 4:</strong> Carrying out the plank exercise</figcaption></figure>
<aside class="activity-panel lower-activity"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 4</div><ol class="alpha-list" type="a"><li>Practice planks individually.</li><li>In pair, compete by doing planks for as many seconds as possible.</li></ol></aside>
'''),
81: ("exercise-method-page page-81", "Sprint drills", r'''
<h1 id="page-title">Speed exercises</h1><p>Speed exercises are basic for players, particularly in football and netball. There are various types of speed-building exercises such as sprint drills, shuttle runs, broad jumps and rope jumps.</p>
<h2>(a)&nbsp; <strong>Sprint drills</strong></h2><p>This exercise increases speed and improves physical fitness on the field.</p><h3>How to do sprint drills:</h3><ol class="roman-steps" type="i"><li>Run fast for 20 to 30 meters as shown in Figure 5.</li><li>Rest for 30 seconds, and then repeat 5 to 10 times.</li></ol>
<figure class="lesson-figure sprint-figure"><img src="images/pg081_im001.jpg" alt="Two children sprint fast on a track during a short-speed running exercise."><figcaption><strong>Figure 5:</strong> Conducting short-speed running exercises</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 5</div><p>Do short, fast sprints of 20 to 30 meters repeatedly.</p></aside>
'''),
82: ("exercise-method-page page-82", "Shuttle runs and broad jumps", r'''
<h2 id="page-title">(b)&nbsp; <strong>Shuttle runs</strong></h2><p>This is a high-intensity exercise that involves sprinting from one point to another point and going back to the starting point. It helps to improve the speed and endurance of the player.</p><h3>How to do shuttle runs:</h3><ol class="roman-steps" type="i"><li>Run from one point to another, touching the ground with your hand each time you change direction, as shown in Figure 6.</li><li>Repeat 5 to 10 times for 3 sets.</li></ol>
<figure class="lesson-figure shuttle-figure"><img src="images/pg082_im001.jpg" alt="A boy runs back and forth between cones for a shuttle run; red arrows show the path out and back."><figcaption><strong>Figure 6:</strong> Doing shuttle runs</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 6</div><ol class="alpha-list" type="a"><li>Do a shuttle run individually.</li><li>In pairs, compete by doing a shuttle run.</li></ol></aside>
<h2>(c)&nbsp; <strong>Broad jumps</strong></h2><p>This exercise increases jumping power and speed. This is important in playing various sports, such as netball and football.</p><h3>How to do broad jumps:</h3><ol class="roman-steps" type="i"><li>Stand upright, then bend your knees slightly;</li><li>Jump forward with force and land on both feet; and</li><li>Repeat 5 to 10 times for 3 sets, by following steps (i-ii) as shown in Figure 7.</li></ol>
'''),
83: ("exercise-method-page page-83", "Broad jump and rope skipping", r'''
<figure class="lesson-figure broad-jump-figure"><img src="images/pg083_im001.jpg" alt="A boy shows the broad jump in three steps: bending down, jumping forward, and landing with knees bent."><figcaption><strong>Figure 7:</strong> Doing the broad jump exercise</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 7</div><ol class="alpha-list" type="a"><li>Do the broad jump exercise individually.</li><li>In groups, practice the broad jump.</li></ol></aside>
<h2 id="page-title">(d)&nbsp; <strong>Rope skipping</strong></h2><p>This is an exercise that helps to improve leg speed and increase stamina. This exercise can be done by rope skipping on one leg or both legs.</p><h3>How to do rope skipping</h3><ol class="roman-steps" type="i"><li>Hold the rope ends with your hands;</li><li>Swing it moving down your feet and above your head as you jump;</li><li>Keep jumping at a faster pace for 60 seconds, then rest for 30 seconds; and</li><li>Repeat 3 to 5 times, by following steps (i-iii) as shown in Figure 8.</li></ol>
'''),
84: ("exercise-method-page page-84", "Rope skipping and traditional games", r'''
<figure class="lesson-figure rope-figure"><div class="diagram-row"><img src="images/pg084_im001_seg001_v1.png" alt="A child jumps while skipping a rope overhead."><img src="images/pg084_im001_seg002_v1.png" alt="A child skips rope as the rope swings under the feet."></div><figcaption><strong>Figure 8:</strong> Doing the rope skipping exercise</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 8</div><ol class="alpha-list" type="a"><li>Do the rope skipping exercise with one leg, then with both legs individually.</li><li>In pairs, compete by doing rope skipping for a long time as possible.</li></ol></aside>
<aside class="exercise-panel"><div class="panel-title">Exercise 1</div><ol class="number-list"><li>Name two exercises that help improve strength for netball and football players.</li><li>Why is speed important for netball and football players?</li><li>Explain how shuttle runs help a player on the field.</li></ol></aside>
<h1 id="page-title">Traditional games</h1><p>Traditional games are important in society because of their social and cultural significance. These games provide people with opportunities to participate,</p>
'''),
}

TEMPLATE='''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Arts and Sports Pupil's Book Standard Five - page {n}</title><meta name="title-id" content="pg{nnn}_sec001"><meta name="page-section-id" content="{n}"><link href="./content/tailwind_output.css" rel="stylesheet"><link href="./assets/libs/fontawesome/css/all.min.css" rel="stylesheet"><link href="./assets/fonts.css" rel="stylesheet"><link href="./assets/book-pages.css?v=20260827-19" rel="stylesheet"></head><body><main><div id="content" class="opacity-0"><section role="article" aria-label="{label}" data-section-type="physical-exercise" data-section-id="pg{nnn}_sec001" class="book-page content-page {classes}"><div class="page-inner">{content}</div>{hooks}</section></div></main><div class="page-voice-controls" aria-label="Page voice controls"><button type="button" data-page-read>Read page</button><button type="button" data-page-stop>Stop</button></div><div class="relative z-50" id="interface-container"></div><div class="relative z-50" id="nav-container"></div><script src="./assets/offline-preloader.js?v=audiofix-20260824-1"></script><script src="./assets/scorm.js"></script><script src="./assets/pdf-page-readalong.js?v=audiofix-20260824-1"></script><script src="./assets/base.bundle.local.js?v=audiofix-20260824-1"></script></body></html>'''
for n,(classes,label,content) in PAGES.items():
 p=ROOT/f"pg{n:03d}_sec001.html";old=p.read_text(encoding="utf-8");m=re.search(r'<div class="[^"]*semantic-page-text[^"]*"[^>]*>.*?</div>',old,re.S)
 if not m: raise RuntimeError(p.name)
 hooks=re.sub(r'class="[^"]*semantic-page-text[^"]*"','class="page-narration-hooks semantic-page-text"',m.group(0),count=1).replace('aria-label="Accessible page text"','aria-hidden="true"')
 p.write_text(TEMPLATE.format(n=n,nnn=f"{n:03d}",label=label,classes=classes,content=content.strip(),hooks=hooks)+"\n",encoding="utf-8");print(p.name)
