from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
PAGES={
85:("game-page page-85","Tug-of-war rules",r'''
<p>have fun, and learn important values. They have been played for centuries, reflecting the needs, traditions, and customs of the respective communities. Often, these games are played using simple and local materials, and their main features is the close interaction between the participants. One of the traditional games is tug-of-war.</p>
<h1 id="page-title">Tug-of-war</h1><p>Tug of war is one of the traditional games played by people of all ages. It is a competitive game that requires strength, teamwork, technique and endurance. Although it is an ancient game, it is still very popular in various communities, especially in school competitions, social celebrations, and in international games. Historically, this game is associated with many cultures around the world. In East Africa, this game has been part of the culture of many communities, associated with physical exercise, entertainment, and festive celebrations to date. The game is popular in school sports’ competitions and cultural concerts.</p>
<h2>Game equipment</h2><p>In playing this game, various equipment are used such as a rope, whistle, lime and flagmaker.</p>
<h2>Rules and regulations of the game</h2><ol class="game-rules"><li><span>Number of players:</span><ol type="a"><li>The teams should have an equal number of players, usually between 3 and 8 people, but the number may vary depending on the competition.</li><li>Players should be in good health and physical strength to participate effectively.</li></ol></li><li><span>Game structure:</span><ol type="a"><li>A long rope with a centre mark is used.</li><li>A centre line is drawn on the ground to indicate the area beyond which either team loses.</li><li>Each team holds its side of the rope tightly and lines up in a neat formation, as shown in Figure 9.</li><li>The referee ensures that both teams are ready before giving the signal to start.</li></ol></li></ol>
'''),
86:("game-page page-86","Tug-of-war strategies",r'''
<figure class="lesson-figure tug-figure"><img src="images/pg086_im001.jpg" alt="Two teams are ready for a tug-of-war, with three children on each side leaning back across the centre line."><figcaption><strong>Figure 9:</strong> Teams ready for tug-of-war</figcaption></figure>
<ol class="game-rules" start="3"><li><span>Method of determining the winner:</span><ol type="a"><li>The team that can pull the rope and move the opposing team across the centre line is declared the winner.</li><li>Sometimes, the game is played in more than one round, and the team that wins the most rounds is awarded the overall winner.</li></ol></li></ol>
<h2 id="page-title">Strategies for winning the game</h2><ol class="strategy-list" type="a"><li><strong>Teamwork.</strong> Working together and planning a pull-up strategy instead of each person pulling independently.</li><li><strong>Organising players in good order.</strong> Some players are strategically placed at the front, middle, and back to provide maximum support for the team. For instance, the strongest players may be placed at the front, middle and back.</li><li><strong>Holding the rope strongly and tightly.</strong> Players should hold the rope strongly and tightly and keep their hands close to their bodies for stability.</li><li><strong>Using one back leg as the main force.</strong> Players should place one foot behind to gain good footing and pulling power, as shown in Figure 10.</li><li><strong>Preventing slipping.</strong> Wearing shoes that provide good traction on the ground helps prevent slipping.</li></ol>
'''),
87:("game-page page-87","Benefits of tug-of-war",r'''
<figure class="lesson-figure tug-action"><img src="images/pg087_im001.jpg" alt="A tug-of-war team leans back and pulls the rope, with their feet spread wide for balance."><figcaption><strong>Figure 10:</strong> The feet positioning</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 9</div><ol class="alpha-list" type="a"><li>In pairs, practise a tug-of-war game.</li><li>In teams, play a tug-of-war game.</li></ol></aside>
<h2 id="page-title">Benefits of tug-of-war</h2><ol class="number-list"><li>Help strengthen the muscles of the arms, legs, back and shoulders.</li><li>It enhances cooperation and strategy-setting skills as a team.</li><li>Increases the spirit of competing fairly and enjoying victory wisely.</li><li>It is a good entertainment for children and adults.</li><li>It teaches patience and discipline.</li></ol>
<aside class="exercise-panel"><div class="panel-title">Exercise 2</div><ol class="number-list"><li>Imagine you are on a tug-of-war team. Which position of the team would you like to be (front, middle, or back)? Why?</li><li>Beside strength, what other things are needed to win a tug-of-war?</li><li>What are the potential dangers of playing tug-of-war?</li><li>Outline the precautionary measures of tug-of-war?</li><li>Why is it important for a team to pull the rope together instead of each person pulling separately?</li><li>Which team is declared the winner in tug-of-war?</li></ol></aside>
'''),
88:("chapter-opener-page chapter-seven-page","Chapter Seven: Modern sports",r'''
<header><div class="chapter-banner">Chapter Seven</div><h1 class="chapter-topic" id="page-title">Modern sports</h1></header>
<section class="intro-panel" aria-labelledby="intro-title"><h2 class="panel-title" id="intro-title">Introduction</h2><p>Modern sports are an important part of human life, and to a large extent reflect the history, culture, and technological development of a given society. There are many types of modern sports, including football and netball. In this chapter, you will learn about football and netball. The competencies developed will enable you to play sports in a skilful manner.</p></section>
<aside class="think-panel"><img class="think-icon" src="images/pg088_im001.jpg" alt=""><div class="panel-title">Think</div><p>How to play football and netball</p></aside>
<h2>Football</h2><p>Football is a two-team sport played with the aim of scoring goals in the opponents’ goal. Each team has 11 players, including the goalkeeper. The game requires speed, concentration, and teamwork. The main objective is to score more goals than the opposing team. To score a goal, the ball must cross the goal line.</p>
'''),
89:("football-page page-89","Football equipment and basic skills",r'''
<h1 id="page-title">Equipment</h1><p>To play football correctly, the following equipment are necessary:</p>
<figure class="lesson-figure equipment-figure"><div class="equipment-grid"><div><img src="images/pg089_im001.jpg" alt="A black and white football."><span>Football</span></div><div><span class="shoe-pair"><img src="images/pg089_im002_seg001_v1.png" alt="A football shoe with studs."><img src="images/pg089_im002_seg002_v1.png" alt="The bottom of a football shoe with studs for grip."></span><span>Football shoes</span></div><div><img src="images/pg089_im003.jpg" alt="A pair of blue shin guards."><span>Shin guards</span></div><div><img src="images/pg089_im004.jpg" alt="A pair of long blue football socks."><span>Socks</span></div><div><img src="images/pg089_im005.jpg" alt="A pair of goalkeeper gloves."><span>Goalkeeper gloves</span></div><div><img src="images/pg089_im006.jpg" alt="A football jersey and shorts."><span>Jersey</span></div></div><figcaption><strong>Figure 1:</strong> Football equipment</figcaption></figure>
<aside class="exercise-panel"><div class="panel-title">Exercise 1</div><ol class="number-list"><li>Explain the use of the football equipment shown in Figure 1.</li></ol></aside>
<h2>Basic skills in football</h2><p>To be able to play football well, a player must have the basic skills used in the game. These skills are essential for any player who wants to succeed in football. Among the basic skills in football are passing, receiving the ball, dribbling, shooting, and defending.</p>
'''),
90:("football-page page-90","Passing in football",r'''
<h1 id="page-title">(a) <strong>Passing</strong></h1><p>Passing is the intentional kicking or heading the ball from one player to another of the same team. This is a basic skill of the ball exchange between players of the same team to increase opportunities for attacking or defending. Accurate passing is essential for a team to be able to make quick attacks and reduce the opponent’s chances of winning the ball. Players need to know the time and distance required for each pass, and also have good communication to reduce mistakes. There are two main types of passes: short passes and long passes.</p>
<h2>Short passes</h2><p>A short pass is the kicking or heading of the ball to a teammate who is at a short distance. Normally, this pass is made with the inside of the foot, as shown in Figure 2.</p>
<figure class="lesson-figure football-action"><img src="images/pg090_im001.jpg" alt="A player shows how to make a short pass by kicking the ball with the inside of the foot."><figcaption><strong>Figure 2:</strong> Kicking a short pass</figcaption></figure>
<aside class="activity-panel"><img class="activity-icon" src="images/pg079_im001.png" alt=""><div class="panel-title">Activity 1</div><p>In pairs, practise passing the ball at short distances using the inside of the foot.</p></aside>
<h2>Long pass</h2><p>A long pass is kicking or heading the ball to a teammate who is at a long distance. This pass is usually made using the top of the foot, as shown in Figure 3.</p>
''')}
TEMPLATE='''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Arts and Sports Pupil's Book Standard Five - page {n}</title><meta name="title-id" content="pg{nnn}_sec001"><meta name="page-section-id" content="{n}"><link href="./content/tailwind_output.css" rel="stylesheet"><link href="./assets/libs/fontawesome/css/all.min.css" rel="stylesheet"><link href="./assets/fonts.css" rel="stylesheet"><link href="./assets/book-pages.css?v=20260827-21" rel="stylesheet"></head><body><main><div id="content" class="opacity-0"><section role="article" aria-label="{label}" data-section-type="semantic-book-page" data-section-id="pg{nnn}_sec001" class="book-page content-page {classes}"><div class="page-inner">{content}</div>{hooks}</section></div></main><div class="page-voice-controls" aria-label="Page voice controls"><button type="button" data-page-read>Read page</button><button type="button" data-page-stop>Stop</button></div><div class="relative z-50" id="interface-container"></div><div class="relative z-50" id="nav-container"></div><script src="./assets/offline-preloader.js?v=audiofix-20260824-1"></script><script src="./assets/scorm.js"></script><script src="./assets/pdf-page-readalong.js?v=audiofix-20260824-1"></script><script src="./assets/base.bundle.local.js?v=audiofix-20260824-1"></script></body></html>'''
for n,(classes,label,content) in PAGES.items():
 p=ROOT/f"pg{n:03d}_sec001.html";old=p.read_text(encoding="utf-8");m=re.search(r'<div class="[^"]*semantic-page-text[^"]*"[^>]*>.*?</div>',old,re.S)
 if not m: raise RuntimeError(p.name)
 hooks=re.sub(r'class="[^"]*semantic-page-text[^"]*"','class="page-narration-hooks semantic-page-text"',m.group(0),count=1).replace('aria-label="Accessible page text"','aria-hidden="true"')
 p.write_text(TEMPLATE.format(n=n,nnn=f"{n:03d}",label=label,classes=classes,content=content.strip(),hooks=hooks)+"\n",encoding="utf-8");print(p.name)
